version: '3.8'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - "9890:15672"  # Interfaz web de RabbitMQ
      - "8888:5672"   # Puerto de conexión de RabbitMQ
    hostname: stats
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia  # Volumen persistente
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_network

  sender:
    build:
      context: ./app_sms
      dockerfile: Dockerfile
    container_name: php_sender
    depends_on:
      - rabbitmq
    volumes:
      - ./app_sms:/var/www/html
    working_dir: /var/www/html
    networks:
      - rabbitmq_network
    ports:
      - "8080:80"  # Exponer el servidor web

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Configuración de Prometheus
    ports:
      - "9090:9090"  # Interfaz web de Prometheus
    networks:
      - rabbitmq_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"  # Interfaz web de Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  grafana_data:
    driver: local
