version: '3.8'

services:
  rabbitmq:
    build:
      context: ./  # Ruta a tu directorio donde está el Dockerfile de RabbitMQ
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - 9890:15672  # Interfaz de gestión de RabbitMQ
      - 8888:5672   # Puerto estándar de RabbitMQ
    hostname: stats
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia  
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host

  app_email:
    build:
      context: ./app_sms
      dockerfile: Dockerfile
    container_name: app_email
    networks:
      - rabbitmq_net
    depends_on:
      - rabbitmq  
    ports:
      - "8080:80"  
    volumes:
      - ./app_email/src:/var/www/html  
    environment:
      - RABBITMQ_HOST=rabbitmq  

networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge

volumes:
  rabbitmq_data:
