services:
  rabbitmq:
    build:
      context: .  # Usa el Dockerfile.rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - "9890:15672"  # Interfaz web de RabbitMQ
      - "8888:5672"   # Puerto de conexión de RabbitMQ
    hostname: stats
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia  
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
