services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    restart: always
    ports:
      - "9890:15672"
      - "8888:5672"
      - "15692:15692"
    hostname: stats
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
    networks:
      - rabbitmq_network

  app_email:
    build:
      context: ./app_email
      dockerfile: Dockerfile
    container_name: php_email
    depends_on:
      - rabbitmq
    volumes:
      - ./app_email:/var/www/html
    working_dir: /var/www/html
    networks:
      - rabbitmq_network
    ports:
      - "8082:80"

  app_whatsapp:
    build:
      context: ./app_whatsapp
      dockerfile: Dockerfile
    container_name: php_whatsapp
    depends_on:
      - rabbitmq
    volumes:
      - ./app_whatsapp:/var/www/html
    working_dir: /var/www/html
    networks:
      - rabbitmq_network
    ports:
      - "8083:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - rabbitmq_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  grafana_data:
    driver: local
