global:
  scrape_interval: 5s  # Intervalo de recopilación de métricas

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']  # Conectar Prometheus con RabbitMQ
